import { NextRequest, NextResponse } from 'next/server'
import { isAuthenticatedFromRequest } from '@/lib/session/session'
import type { APLevel, ConfidenceLevel, FmeaRow, FmeaValidationResult, IssueSeverity } from '@/modules/fmea/types'

export const runtime = 'nodejs'
export const maxDuration = 60

interface ExportPdfRequest {
  validationResult: FmeaValidationResult
  rows: FmeaRow[]
  language?: 'de' | 'en'
  companyName?: string
}

const LABELS = {
  en: {
    title: 'FMEA Review Report',
    summaryTitle: 'Executive Summary',
    generated: 'Generated',
    company: 'Company',
    totalRows: 'Total Rows',
    validRows: 'Valid Rows',
    issueRows: 'Rows with Issues',
    completeness: 'Completeness Score',
    apCompliance: 'AP Compliance Score',
    apMismatches: 'AP Mismatches',
    reviewSection: 'FMEA Review Details',
    issuesSection: 'Validation Issues',
    aiFindingsSection: 'AI Findings',
    recommendedAction: 'Recommended Action',
    row: 'Row',
    failureMode: 'Failure Mode',
    cause: 'Cause',
    sod: 'S/O/D',
    ap: 'AP',
    expected: 'Expected',
    severity: 'Severity',
    field: 'Field',
    page: 'Page',
    disclaimer: 'This report was generated by IATF Solutions FMEA Reviewer. Always verify against the latest AIAG/VDA source documents.',
  },
  de: {
    title: 'FMEA-Pruefbericht',
    summaryTitle: 'Zusammenfassung',
    generated: 'Erstellt',
    company: 'Unternehmen',
    totalRows: 'Gesamtzeilen',
    validRows: 'Gueltige Zeilen',
    issueRows: 'Zeilen mit Problemen',
    completeness: 'Vollstaendigkeitsscore',
    apCompliance: 'AP-Compliance-Score',
    apMismatches: 'AP-Abweichungen',
    reviewSection: 'FMEA Review-Details',
    issuesSection: 'Validierungsprobleme',
    aiFindingsSection: 'AI Findings',
    recommendedAction: 'Empfohlene Massnahme',
    row: 'Zeile',
    failureMode: 'Fehlerart',
    cause: 'Ursache',
    sod: 'S/O/D',
    ap: 'AP',
    expected: 'Soll',
    severity: 'Schwere',
    field: 'Feld',
    page: 'Seite',
    disclaimer: 'Dieser Bericht wurde mit dem IATF Solutions FMEA Reviewer erstellt. Bitte stets mit den aktuellen AIAG/VDA-Quelldokumenten abgleichen.',
  },
} as const

const BRAND_COLOR = '#1d4ed8'
const BRAND_COLOR_DARK = '#1e3a5f'
const PAGE_W = 595
const MARGIN = 40
const CONTENT_W = PAGE_W - MARGIN * 2

const AP_LABELS: Record<APLevel, string> = {
  H: 'High',
  M: 'Medium',
  L: 'Low',
}

type FmeaAiFinding = {
  row_id: string
  ruleId: string
  title: string
  explanation: string
  recommended_action: string
  confidence: ConfidenceLevel
}

function severityColor(severity: IssueSeverity) {
  if (severity === 'Critical') return '#dc2626'
  if (severity === 'High') return '#ea580c'
  return '#ca8a04'
}

function apColor(ap?: APLevel) {
  if (ap === 'H') return '#dc2626'
  if (ap === 'M') return '#ca8a04'
  if (ap === 'L') return '#16a34a'
  return '#64748b'
}

function apText(ap?: APLevel) {
  if (!ap) return '-'
  return `${ap} (${AP_LABELS[ap]})`
}

function issueSummaryRows(summary: FmeaValidationResult['issue_summaries'][number]): string {
  return summary.source_rows.length > 0
    ? summary.source_rows.join(', ')
    : summary.row_ids.join(', ')
}

function isFmeaAiFinding(value: unknown): value is FmeaAiFinding {
  if (!value || typeof value !== 'object') return false
  const candidate = value as Partial<FmeaAiFinding>
  return (
    typeof candidate.row_id === 'string' &&
    typeof candidate.ruleId === 'string' &&
    typeof candidate.title === 'string' &&
    typeof candidate.explanation === 'string' &&
    typeof candidate.recommended_action === 'string' &&
    typeof candidate.confidence === 'string'
  )
}

function getAiFindings(validationResult: FmeaValidationResult): FmeaAiFinding[] {
  return Array.isArray(validationResult.ai_findings)
    ? validationResult.ai_findings.filter(isFmeaAiFinding)
    : []
}

export async function POST(request: NextRequest) {
  if (!(await isAuthenticatedFromRequest(request))) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body: ExportPdfRequest
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const {
    validationResult,
    rows,
    language = 'en',
    companyName = 'IATF Organization',
  } = body

  if (!validationResult || !Array.isArray(rows)) {
    return NextResponse.json({ error: 'Invalid data' }, { status: 400 })
  }

  const L = LABELS[language] ?? LABELS.en
  const aiFindings = getAiFindings(validationResult)
  const issueSummaries = Array.isArray(validationResult.issue_summaries)
    ? validationResult.issue_summaries
    : []

  try {
    const PDFDocument = (await import('pdfkit')).default
    const chunks: Buffer[] = []
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 60, left: MARGIN, right: MARGIN },
      info: {
        Title: L.title,
        Author: 'IATF Solutions',
        Creator: 'FMEA Reviewer',
      },
      autoFirstPage: false,
    })

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    const finished = new Promise<void>((resolve) => doc.on('end', resolve))
    let pageNum = 0

    function drawFooter() {
      const oldX = doc.x
      const oldY = doc.y
      const oldMarginBottom = doc.page.margins.bottom
      doc.page.margins.bottom = 0
      const footerY = doc.page.height - 35
      doc.save()
      doc.fontSize(7).fillColor('#94a3b8').font('Helvetica')
      doc.text(L.title, MARGIN, footerY, { width: CONTENT_W * 0.6, align: 'left', lineBreak: false })
      doc.text(`${L.page} ${pageNum}`, MARGIN, footerY, { width: CONTENT_W, align: 'right', lineBreak: false })
      doc.restore()
      doc.page.margins.bottom = oldMarginBottom
      doc.x = oldX
      doc.y = oldY
    }

    doc.on('pageAdded', () => {
      pageNum++
      drawFooter()
    })

    function newPage() {
      doc.addPage()
    }

    function sectionHeader(text: string, color = BRAND_COLOR) {
      if (doc.y > 680) newPage()
      doc.rect(MARGIN, doc.y, CONTENT_W, 20).fill(color)
      const oldY = doc.y
      doc.fontSize(11).fillColor('#ffffff').font('Helvetica-Bold')
        .text(text, MARGIN + 6, oldY + 5, { width: CONTENT_W - 12 })
      doc.y = oldY + 28
    }

    newPage()

    doc.fontSize(8).fillColor('#94a3b8').font('Helvetica')
      .text('IATF Solutions', MARGIN, MARGIN + 5, { width: CONTENT_W, align: 'right' })

    const titleY = 90
    doc.rect(MARGIN, titleY, CONTENT_W, 56).fill(BRAND_COLOR)
    doc.fontSize(18).fillColor('#ffffff').font('Helvetica-Bold')
      .text(L.title, MARGIN + 12, titleY + 10, { width: CONTENT_W - 24, align: 'center' })
    doc.fontSize(10).fillColor('#bfdbfe').font('Helvetica')
      .text(L.summaryTitle, MARGIN + 12, titleY + 36, { width: CONTENT_W - 24, align: 'center' })

    doc.y = titleY + 76
    doc.fontSize(10).fillColor('#334155')
    const meta: [string, string][] = [
      [L.generated, new Date().toLocaleDateString(language === 'de' ? 'de-DE' : 'en-GB')],
      [L.company, companyName],
    ]
    for (const [label, value] of meta) {
      doc.font('Helvetica-Bold').text(`${label}: `, { continued: true })
      doc.font('Helvetica').text(value)
    }
    doc.moveDown(1.5)

    const statItems: [string, number | string, string][] = [
      [L.totalRows, validationResult.rows_total, '#1d4ed8'],
      [L.validRows, validationResult.rows_valid, '#16a34a'],
      [L.issueRows, validationResult.rows_with_issues, '#ea580c'],
      [L.apMismatches, validationResult.ap_mismatches.length, '#dc2626'],
    ]
    const cellW = CONTENT_W / 4
    const statY = doc.y
    for (let i = 0; i < statItems.length; i++) {
      const [label, count, color] = statItems[i]
      const x = MARGIN + i * cellW
      doc.rect(x, statY, cellW - 4, 52).fill('#f8fafc')
      doc.fontSize(22).fillColor(color).font('Helvetica-Bold')
        .text(String(count), x + 4, statY + 6, { width: cellW - 8, align: 'center' })
      doc.fontSize(8).fillColor('#64748b').font('Helvetica')
        .text(label, x + 4, statY + 34, { width: cellW - 8, align: 'center' })
    }
    doc.y = statY + 70

    doc.fontSize(9).fillColor('#334155').font('Helvetica-Bold')
      .text(`${L.completeness}: `, { continued: true })
    doc.font('Helvetica').text(`${validationResult.completeness_score}%`)

    doc.fontSize(9).fillColor('#334155').font('Helvetica-Bold')
      .text(`${L.apCompliance}: `, { continued: true })
    doc.font('Helvetica').text(`${validationResult.ap_compliance_score}%`)


    // Risk Breakdown - Bar Chart Style (matching CSR)
    doc.moveDown(1.5)
    
    const riskBreakdownHeaderY = doc.y
    const headerHeight = 18
    
    // Blue header background (matching CSR)
    doc.rect(MARGIN, riskBreakdownHeaderY, CONTENT_W, headerHeight).fill('#1e40af')
    
    // Header text
    doc.fontSize(11).fillColor('#ffffff').font('Helvetica-Bold')
      .text(language === 'de' ? 'Risiko-Verteilung' : 'Risk Breakdown', MARGIN + 8, riskBreakdownHeaderY + 2)
    
    doc.y = riskBreakdownHeaderY + headerHeight + 10

    const severityStats = validationResult.statistics.issues_by_severity
    
    const allChartData = [
      { 
        label: language === 'de' ? 'Kritisch' : 'Critical', 
        count: severityStats.Critical,
        color: '#dc2626'
      },
      { 
        label: language === 'de' ? 'Hoch' : 'High', 
        count: severityStats.High,
        color: '#ea580c'
      },
      { 
        label: language === 'de' ? 'Mittel' : 'Medium', 
        count: severityStats.Medium,
        color: '#ca8a04'
      }
    ]
    
    // Filter out items with count = 0
    const chartData = allChartData.filter(item => item.count > 0)
    
    // If no data, show message
    if (chartData.length === 0) {
      doc.fontSize(9).fillColor('#64748b').font('Helvetica')
        .text(language === 'de' ? 'Keine Probleme gefunden' : 'No issues found')
      doc.moveDown(0.5)
    } else {
      const maxCount = Math.max(...chartData.map(item => item.count), 1)
      
      const chartStartY = doc.y
      const barHeight = 16
      const barSpacing = 12
      const chartWidth = CONTENT_W * 0.65

      chartData.forEach((item, index) => {
        const barY = chartStartY + index * (barHeight + barSpacing)
        const barWidth = (item.count / maxCount) * chartWidth
        
        // Label
        doc.fontSize(9).fillColor('#334155').font('Helvetica')
          .text(item.label, MARGIN, barY, { width: 70, align: 'left' })
        
        // Bar background
        doc.rect(MARGIN + 75, barY, chartWidth, barHeight).fill('#e2e8f0')
        
        // Bar fill
        doc.rect(MARGIN + 75, barY, barWidth, barHeight).fill(item.color)
        
        // Count text
        doc.fontSize(8).fillColor('#ffffff').font('Helvetica-Bold')
          .text(String(item.count), MARGIN + 75 + Math.max(barWidth - 25, 5), barY + 3, { width: 20, align: 'right' })
      })
      
      doc.y = chartStartY + chartData.length * (barHeight + barSpacing)
    }

    newPage()
    sectionHeader(L.reviewSection)
    const colX = [MARGIN, MARGIN + 44, MARGIN + 178, MARGIN + 292, MARGIN + 342, MARGIN + 406]
    const colW = [40, 130, 110, 46, 58, 104]
    const headers = [L.row, L.failureMode, L.cause, L.sod, L.ap, L.expected]

    function drawTableHeader() {
      doc.rect(MARGIN, doc.y - 2, CONTENT_W, 16).fill(BRAND_COLOR)
      const y = doc.y
      doc.fillColor('#ffffff').fontSize(7).font('Helvetica-Bold')
      headers.forEach((header, index) => {
        doc.text(header, colX[index], y, { width: colW[index], align: 'left' })
      })
      doc.y = y + 18
      doc.fillColor('#334155').font('Helvetica')
    }

    drawTableHeader()
    rows.slice(0, 120).forEach((row, index) => {
      const mismatch = validationResult.ap_mismatches.find((item) => item.row_id === row.id)
      const values = [
        String(row.source_reference.row),
        row.failure_mode || '-',
        row.failure_cause || '-',
        `${row.severity}/${row.occurrence}/${row.detection}`,
        apText(row.ap_current),
        apText(mismatch?.expected_ap ?? row.ap_current),
      ]
      doc.fontSize(6.5).font('Helvetica')
      const rowH = Math.max(...values.map((value, idx) => doc.heightOfString(value, { width: colW[idx] }))) + 5
      if (doc.y + rowH > 730) {
        newPage()
        drawTableHeader()
      }
      const y = doc.y
      if (index % 2 === 1) doc.rect(MARGIN, y - 1, CONTENT_W, rowH).fill('#f8fafc')
      values.forEach((value, idx) => {
        doc.fillColor(idx === 4 || idx === 5 ? apColor(idx === 4 ? row.ap_current : (mismatch?.expected_ap ?? row.ap_current)) : '#334155')
          .text(value, colX[idx], y, { width: colW[idx] })
      })
      doc.y = y + rowH
    })

    newPage()
    sectionHeader(L.issuesSection, BRAND_COLOR_DARK)
    if (validationResult.issues.length === 0) {
      doc.fontSize(9).fillColor('#64748b').font('Helvetica').text('No validation issues detected.')
    } else {
      if (issueSummaries.length > 0) {
        doc.fontSize(9).fillColor('#334155').font('Helvetica-Bold')
          .text(language === 'de' ? 'Aggregierte Befunde' : 'Aggregated Findings')
        doc.moveDown(0.3)
        issueSummaries.forEach((summary) => {
          if (doc.y > 700) newPage()
          doc.fontSize(8).fillColor(severityColor(summary.severity)).font('Helvetica-Bold')
            .text(`${summary.ruleId} | ${summary.field}: `, { continued: true })
          doc.fillColor('#334155').font('Helvetica').text(summary.summary)
          doc.fontSize(7).fillColor('#64748b').font('Helvetica')
            .text(`${L.row}: ${issueSummaryRows(summary)}`)
          doc.moveDown(0.5)
        })
      }
    }

    if (aiFindings.length) {
      newPage()
      sectionHeader(L.aiFindingsSection, BRAND_COLOR_DARK)
      aiFindings.slice(0, 80).forEach((finding) => {
        if (doc.y > 690) newPage()
        const y = doc.y
        doc.rect(MARGIN, y, CONTENT_W, 15).fill('#eff6ff')
        doc.fontSize(8).fillColor(BRAND_COLOR).font('Helvetica-Bold')
          .text(`${finding.ruleId} | ${finding.row_id} | ${finding.confidence}`, MARGIN + 4, y + 4, { width: CONTENT_W - 8 })
        doc.y = y + 20
        doc.fontSize(8).fillColor('#111827').font('Helvetica-Bold')
          .text(finding.title, MARGIN, doc.y, { width: CONTENT_W })
        doc.moveDown(0.25)
        doc.fontSize(7.5).fillColor('#475569').font('Helvetica')
          .text(finding.explanation, MARGIN, doc.y, { width: CONTENT_W })
        doc.moveDown(0.25)
        doc.fontSize(7.5).fillColor('#334155').font('Helvetica-Bold')
          .text(`${L.recommendedAction}: `, MARGIN, doc.y, { continued: true })
        doc.font('Helvetica').text(finding.recommended_action, { width: CONTENT_W })
        doc.moveDown(0.8)
      })
    }

    if (doc.y > 720) newPage()
    doc.moveDown(2)
    doc.fontSize(6.5).fillColor('#94a3b8').font('Helvetica')
      .text(L.disclaimer, MARGIN, doc.y, { width: CONTENT_W, align: 'center' })

    doc.end()
    await finished

    const buffer = Buffer.concat(chunks)
    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="FMEA_Review_Summary.pdf"',
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    console.error('[FMEA Export] PDF generation failed:', err)
    return NextResponse.json({ error: 'PDF generation failed' }, { status: 500 })
  }
}
