export const csrInfoSeedDataEn = {
  heroBadge: 'IATF 16949 Compliance',
  backToHome: 'Back to Home',
  heroTitle: 'The Intelligent',
  heroTitleHighlight: 'CSR Matrix',
  heroDescription: 'Streamline your QMS by automatically merging IATF 16949 requirements with the latest Customer Specific Requirements (CSR) from all major OEMs.',
  ctaCredits: 'Buy credits',
  ctaBuy: 'Create Your Matrix',
  ctaSample: 'Download Sample',
  sampleDownload: 'Download Sample (PDF)',
  sampleCta: 'Generate Yours Now',
  sampleLabel: 'SAMPLE REPORT',
  sampleTitle: 'See the precision for yourself',
  sampleDesc: 'Download our comprehensive sample report to see how we map IATF 16949 requirements directly to OEM specifics and your internal processes.',
  trust1: 'All Major OEMs (BMW, VW, etc.)',
  trust2: 'Updated Weekly',
  trust3: 'AI-Powered Mapping',
  trust4: 'Audit-Ready Export',
  trust5: 'No Subscription',
  outputLabel: 'PROFESSIONAL OUTPUT',
  outputBadge: 'INCLUDED',
  outputPdfTitle: 'Executive PDF Summary',
  outputPdfDesc: 'A high-level overview of your compliance landscape and risk profile, ready for management review.',
  outputExcelTitle: 'Master Excel Matrix',
  outputExcelDesc: 'Detailed mapping, implementation tracking, and gap analysis in a professional, filterable format.',
  disciplinesLabel: 'CORE CAPABILITIES',
  disciplinesTitle: 'Everything you need for CSR compliance',
  disciplinesSub: 'Our generator covers every aspect of managing Customer Specific Requirements, from initial mapping to audit preparation.',
  d1Title: 'Central Database',
  d1Desc: 'Access the latest requirements from BMW, Mercedes, VW, Ford, and more in one place.',
  d2Title: 'AI Mapping',
  d2Desc: 'Upload your process map and let AI automatically link requirements to your specific departments.',
  d3Title: 'Conflict Detection',
  d3Desc: 'Spot contradictions between different OEM requirements on the same IATF chapters instantly.',
  d4Title: 'Risk Assessment',
  d4Desc: 'Requirements are categorized by risk level (Critical to Low) to prioritize your actions.',
  d5Title: 'Gap Analysis',
  d5Desc: 'Track implementation status and document evidence directly within the matrix preview.',
  d6Title: 'Audit Readiness',
  d6Desc: 'Export professional files that meet the strictest requirements of IATF 16949 audits.',
  d7Title: 'Version Delta',
  d7Desc: 'Automatically compare with older versions to see what\'s new, changed, or removed.',
  d8Title: 'Multi-Language',
  d8Desc: 'Generate your matrix in English or German with a single click, perfectly translated.',
  howLabel: 'SIMPLE PROCESS',
  howTitle: 'From Selection to Export in 3 Steps',
  step1Title: 'Select OEMs',
  step1Desc: 'Choose your customers and the relevant IATF 16949 chapters you want to cover.',
  step2Title: 'Define Processes',
  step2Desc: 'Upload your process landscape or use our automotive template for AI mapping.',
  step3Title: 'Export & Audit',
  step3Desc: 'Review the generated matrix, set implementation status, and download your files.',
  pricingLabel: 'TRANSPARENT PRICING',
  pricingTitle: 'One credit per CSR Matrix',
  pricingSub: 'Simple, transparent options.',
  popularBadge: 'MOST POPULAR',
  plan1Credits: '1 CREDIT',
  plan1Price: '299',
  plan1Per: 'per CSR Matrix',
  plan1Feature1: 'All OEMs included',
  plan1Feature2: 'AI-Powered Analysis',
  plan1Feature3: 'Excel & PDF Export',
  plan1Feature4: '24h Session Access',
  plan2Credits: '5 PACK',
  plan2Price: 'On request',
  plan2Per: 'Custom pricing',
  plan2Feature1: '5 generations',
  plan2Feature2: 'Most popular',
  plan2Feature3: 'Best value',
  plan3Credits: '20 PACK',
  plan3Price: 'On request',
  plan3Per: 'Custom pricing',
  plan3Feature1: '20 generations',
  plan3Feature2: 'Bulk deal',
  plan3Feature3: 'For teams',
  pricingNote: 'Prices in EUR plus VAT where applicable. Instant credit delivery after payment.',
  faqLabel: 'FREQUENTLY ASKED QUESTIONS',
  faq1Q: 'Which OEMs are included in the database?',
  faq1A: 'We cover all major automotive OEMs including BMW, Volkswagen Group (Audi, Porsche, etc.), Mercedes-Benz, Ford, Stellantis, and many Tier-1 suppliers.',
  faq2Q: 'How often is the requirement database updated?',
  faq2A: 'Our database is monitored weekly for new OEM releases and Sanctioned Interpretations (SIs) from the IATF. Updates are pushed automatically to the generator.',
  faq3Q: 'Can I use my own process map?',
  faq3A: 'Yes! You can upload an image of your process map or enter your processes manually. Our AI will handle the mapping to the CSR requirements.',
  faq4Q: 'What format are the exports in?',
  faq4A: 'You receive a professional Excel file (.xlsx) with multiple tabs (Matrix, Conflicts, Owners) and a high-level PDF summary report.',
  faq5Q: 'Do I need a subscription?',
  faq5A: 'No. We believe in pay-per-use. You buy credits and only spend them when you actually generate a new matrix or a major update.',
  finalCtaTitle: 'Ready to master your CSRs?',
  finalCtaDesc: 'Join hundreds of quality managers who have automated their CSR mapping and audit preparation.',
  finalCtaBuy: 'Buy Credits',
  finalCtaGetStarted: 'Get Started',
  cookiePolicyTitle: 'Cookie Policy & Consent',
  docHeaderTitle: 'CSR MATRIX',
  docHeaderSub: 'Quality Compliance',
  docD1: 'OEM Requirements',
  docD2: 'Process Mapping',
  docD4: 'Risk Profile',
  docD5D8: 'Gap Analysis',
  metaTitle: 'CSR Matrix | IATF Solutions',
  metaDescription: 'Streamline your QMS by automatically merging IATF 16949 requirements with the latest Customer Specific Requirements (CSR) from all major OEMs.'
}

export const csrInfoSeedDataDe = {
  heroBadge: 'IATF 16949 Compliance',
  backToHome: 'Zurück zur Übersicht',
  heroTitle: 'Die intelligente',
  heroTitleHighlight: 'CSR Matrix',
  heroDescription: 'Optimieren Sie Ihr QMS, indem Sie IATF 16949 Anforderungen automatisch mit den neuesten kundenspezifischen Anforderungen (CSR) aller großen OEMs zusammenführen.',
  ctaCredits: 'Credits kaufen',
  ctaBuy: 'Matrix erstellen',
  ctaSample: 'Beispiel laden',
  sampleDownload: 'Beispiel laden (PDF)',
  sampleCta: 'Jetzt Matrix erstellen',
  sampleLabel: 'BEISPIELAUSGABE',
  sampleTitle: 'Überzeugen Sie sich selbst',
  sampleDesc: 'Laden Sie eine Beispiel-CSR-Matrix herunter, um die Detailtiefe, Formatierung und KI-Mapping-Qualität zu sehen.',
  trust1: 'Alle großen OEMs (BMW, VW, etc.)',
  trust2: 'Wöchentliche Updates',
  trust3: 'KI-gestützte Zuordnung',
  trust4: 'Audit-fähiger Export',
  trust5: 'Kein Abonnement',
  outputLabel: 'PROFESSIONELLE AUSGABE',
  outputBadge: 'INKLUSIVE',
  outputPdfTitle: 'Executive PDF Summary',
  outputPdfDesc: 'Ein hochgradiger Überblick über Ihre Compliance-Landschaft und Ihr Risikoprofil, bereit für das Management-Review.',
  outputExcelTitle: 'Master Excel Matrix',
  outputExcelDesc: 'Detaillierte Zuordnung, Umsetzungsverfolgung und Gap-Analyse in einem professionellen, filterbaren Format.',
  disciplinesLabel: 'KERNKOMPETENZEN',
  disciplinesTitle: 'Alles, was Sie für die CSR-Compliance benötigen',
  disciplinesSub: 'Unser Generator deckt jeden Aspekt der Verwaltung kundenspezifischer Anforderungen ab, von der ersten Zuordnung bis zur Audit-Vorbereitung.',
  d1Title: 'Zentrale Datenbank',
  d1Desc: 'Greifen Sie an einem Ort auf die neuesten Anforderungen von BMW, Mercedes, VW, Ford und weiteren zu.',
  d2Title: 'KI-Mapping',
  d2Desc: 'Laden Sie Ihre Prozesslandkarte hoch und lassen Sie die KI automatisch Anforderungen mit Ihren Abteilungen verknüpfen.',
  d3Title: 'Konflikterkennung',
  d3Desc: 'Erkennen Sie sofort Widersprüche zwischen verschiedenen OEM-Anforderungen zu denselben IATF-Kapiteln.',
  d4Title: 'Risikobewertung',
  d4Desc: 'Anforderungen werden nach Risikostufe kategorisiert (Kritisch bis Niedrig), um Ihre Maßnahmen zu priorisieren.',
  d5Title: 'Gap-Analyse',
  d5Desc: 'Verfolgen Sie den Umsetzungsstatus und dokumentieren Sie Nachweise direkt in der Matrix-Vorschau.',
  d6Title: 'Audit-Bereitschaft',
  d6Desc: 'Exportieren Sie professionelle Dateien, die den strengsten Anforderungen von IATF 16949 Audits entsprechen.',
  d7Title: 'Versions-Delta',
  d7Desc: 'Vergleichen Sie automatisch mit älteren Versionen, um zu sehen, was neu ist, geändert wurde oder weggefallen ist.',
  d8Title: 'Mehrsprachigkeit',
  d8Desc: 'Generieren Sie Ihre Matrix mit einem Klick auf Englisch oder Deutsch, perfekt übersetzt.',
  howLabel: 'EINFACHER PROZESS',
  howTitle: 'In 3 Schritten von der Auswahl zum Export',
  step1Title: 'OEMs auswählen',
  step1Desc: 'Wählen Sie Ihre Kunden und die relevanten IATF 16949 Kapitel aus, die Sie abdecken möchten.',
  step2Title: 'Prozesse definieren',
  step2Desc: 'Laden Sie Ihre Prozesslandschaft hoch oder nutzen Sie unsere Vorlage für das KI-Mapping.',
  step3Title: 'Export & Audit',
  step3Desc: 'Prüfen Sie die Matrix, setzen Sie den Status und laden Sie Ihre audit-fähigen Dateien herunter.',
  pricingLabel: 'TRANSPARENTE PREISE',
  pricingTitle: 'Ein Credit pro CSR-Matrix',
  pricingSub: 'Einfache, transparente Optionen.',
  popularBadge: 'AM BELIEBTESTEN',
  plan1Credits: '1 CREDIT',
  plan1Price: '299',
  plan1Per: 'pro CSR-Matrix',
  plan1Feature1: 'Alle OEMs inklusive',
  plan1Feature2: 'KI-gestützte Analyse',
  plan1Feature3: 'Excel & PDF Export',
  plan1Feature4: '24h Sitzungszugriff',
  plan2Credits: '5 PACK',
  plan2Price: 'Auf Anfrage',
  plan2Per: 'Individuelle Preise',
  plan2Feature1: '5 Generierungen',
  plan2Feature2: 'Am beliebtesten',
  plan2Feature3: 'Bester Wert',
  plan3Credits: '20 PACK',
  plan3Price: 'Auf Anfrage',
  plan3Per: 'Individuelle Preise',
  plan3Feature1: '20 Generierungen',
  plan3Feature2: 'Mengenrabatt',
  plan3Feature3: 'Für Teams',
  pricingNote: 'Preise in EUR zzgl. MwSt. falls zutreffend. Sofortige Credit-Lieferung nach Zahlung.',
  faqLabel: 'HÄUFIG GESTELLTE FRAGEN',
  faq1Q: 'Welche OEMs sind in der Datenbank enthalten?',
  faq1A: 'Wir decken alle großen Automobil-OEMs ab, einschließlich BMW, Volkswagen Konzern (Audi, Porsche, etc.), Mercedes-Benz, Ford, Stellantis und viele Tier-1-Zulieferer.',
  faq2Q: 'Wie oft wird die Datenbank aktualisiert?',
  faq2A: 'Unsere Datenbank wird wöchentlich auf neue OEM-Veröffentlichungen und Sanctioned Interpretations (SIs) der IATF geprüft. Updates werden automatisch eingespielt.',
  faq3Q: 'Kann ich meine eigene Prozesslandkarte verwenden?',
  faq3A: 'Ja! Sie können ein Bild Ihrer Prozesslandkarte hochladen oder Ihre Prozesse manuell eingeben. Unsere KI übernimmt die Zuordnung zu den CSR-Anforderungen.',
  faq4Q: 'In welchem Format erfolgt der Export?',
  faq4A: 'Sie erhalten eine professionelle Excel-Datei (.xlsx) mit mehreren Tabs (Matrix, Konflikte, Verantwortliche) und einen PDF-Zusammenfassungsbericht.',
  faq5Q: 'Benötige ich ein Abonnement?',
  faq5A: 'Nein. Wir glauben an Pay-per-Use. Sie kaufen Credits und verbrauchen diese nur, wenn Sie tatsächlich eine neue Matrix oder ein größeres Update generieren.',
  finalCtaTitle: 'Bereit, Ihre CSRs zu beherrschen?',
  finalCtaDesc: 'Schließen Sie sich hunderten von Qualitätsmanagern an, die ihre CSR-Mapping und Audit-Vorbereitung automatisiert haben.',
  finalCtaBuy: 'Credits kaufen',
  finalCtaGetStarted: 'Jetzt starten',
  cookiePolicyTitle: 'Cookie-Richtlinie & Einwilligung',
  docHeaderTitle: 'CSR MATRIX',
  docHeaderSub: 'Quality Compliance',
  docD1: 'OEM Anforderungen',
  docD2: 'Prozess-Mapping',
  docD4: 'Risikoprofil',
  docD5D8: 'Gap-Analyse',
  metaTitle: 'CSR Matrix | IATF Solutions',
  metaDescription: 'Optimieren Sie Ihr QMS, indem Sie IATF 16949 Anforderungen automatisch mit den neuesten kundenspezifischen Anforderungen (CSR) aller großen OEMs zusammenführen.'
}

export const eightdInfoSeedDataEn = {
  heroBadge: '8D GENERATOR',
  backToHome: 'Back to Home',
  heroTitle: 'Your IATF-compliant',
  heroTitleHighlight: '8D report in minutes',
  heroDescription: 'Structured problem-solving per IATF 16949 — no Excel chaos, no template hunting. Fill in the fields, AI generates, download PDF and Excel.',
  ctaCredits: 'Buy credits',
  ctaBuy: 'Buy Credits',
  ctaSample: 'Download Sample',
  sampleDownload: 'Download Sample (PDF)',
  sampleCta: 'Generate Yours Now',
  sampleLabel: 'SAMPLE REPORT',
  sampleTitle: 'Professional 8D Output',
  sampleDesc: 'Download our comprehensive 8D sample report to see how we structure problem descriptions, root cause analysis, and corrective actions.',
  trust1: 'IATF 16949 Compliant',
  trust2: 'Audit-Ready Export',
  trust3: 'AI-Guided Analysis',
  trust4: 'PDF & Excel Output',
  trust5: 'No Subscription',
  outputLabel: 'PROFESSIONAL OUTPUT',
  outputBadge: 'INCLUDED',
  outputPdfTitle: 'Official 8D PDF Report',
  outputPdfDesc: 'A beautifully formatted PDF document ready to be sent to your customers or auditors.',
  outputExcelTitle: 'Data-Ready Excel File',
  outputExcelDesc: 'Your 8D data in a clean, filterable Excel format for internal tracking and analysis.',
  disciplinesLabel: 'CORE DISCIPLINES',
  disciplinesTitle: 'All eight disciplines covered',
  disciplinesSub: 'The generator guides you through every discipline and ensures no mandatory field is missed — exactly as auditors and OEMs require.',
  d1Title: 'D1 Team',
  d1Desc: 'Define your problem-solving team and assign roles for the investigation.',
  d2Title: 'D2 Problem',
  d2Desc: 'Structured problem description using 5W2H methodology for maximum clarity.',
  d3Title: 'D3 Containment',
  d3Desc: 'Document immediate actions taken to protect the customer from the defect.',
  d4Title: 'D4 Root Cause',
  d4Desc: 'AI-assisted 5-Why analysis to identify the technical and system root causes.',
  d5Title: 'D5 Corrective Actions',
  d5Desc: 'Define permanent measures to eliminate the root cause once and for all.',
  d6Title: 'D6 Implementation',
  d6Desc: 'Track the status of your actions and document evidence of their execution.',
  d7Title: 'D7 Prevention',
  d7Desc: 'Update FMEA and Control Plans to prevent the recurrence of similar issues.',
  d8Title: 'D8 Recognition',
  d8Desc: 'Finalize the report by acknowledging the team\'s effort and closing the case.',
  howLabel: 'SIMPLE PROCESS',
  howTitle: 'From Upload to Export in 3 Steps',
  step1Title: 'Access Code',
  step1Desc: 'Enter your access code — no account or registration required to start.',
  step2Title: 'Fill in Fields',
  step2Desc: 'Complete the guided input wizard step by step with our intelligent assistance.',
  step3Title: 'Download',
  step3Desc: 'Get your audit-ready PDF and Excel immediately after completing the fields.',
  pricingLabel: 'TRANSPARENT PRICING',
  pricingTitle: 'Simple credit-based access',
  pricingSub: 'One credit per finished 8D report.',
  popularBadge: 'MOST POPULAR',
  plan1Credits: '1 CREDIT',
  plan1Price: '299',
  plan1Per: 'per 8D Report',
  plan1Feature1: 'All 8D disciplines',
  plan1Feature2: 'AI-Powered Analysis',
  plan1Feature3: 'Excel & PDF Export',
  plan1Feature4: '24h Session Access',
  plan2Credits: '5 PACK',
  plan2Price: '1199',
  plan2Per: 'per 5 Reports',
  plan2Feature1: '5 generations',
  plan2Feature2: 'Most popular',
  plan2Feature3: 'Best value',
  plan3Credits: '20 PACK',
  plan3Price: 'On request',
  plan3Per: 'Custom pricing',
  plan3Feature1: '20 generations',
  plan3Feature2: 'Bulk deal',
  plan3Feature3: 'For teams',
  pricingNote: 'Prices in EUR plus VAT where applicable. Instant credit delivery.',
  faqLabel: 'FREQUENTLY ASKED QUESTIONS',
  faq1Q: 'Do I need an account to use the 8D Generator?',
  faq1A: 'No. We use a simple access code system. You can start your report immediately after purchase without creating an account.',
  faq2Q: 'Which languages are supported?',
  faq2A: 'The interface and the generated reports are available in both English and German. You can switch the language at any time.',
  faq3Q: 'How long do I have access to my report?',
  faq3A: 'After entering your code, your session is active for 24 hours. You can download your PDF and Excel files as many times as you like during this period.',
  faq4Q: 'Is the data used to train AI models?',
  faq4A: 'No. Your data is processed securely and is never used to train our AI models. We prioritize data confidentiality for our automotive clients.',
  faq5Q: 'What happens if I need an update later?',
  faq5A: 'A credit covers a single session. If you need to make major changes after your session has expired, a new credit will be required.',
  finalCtaTitle: 'Ready for your first report?',
  finalCtaDesc: 'Join quality managers who have automated their 8D reports and saved hours of manual work.',
  finalCtaBuy: 'Buy Credits',
  finalCtaGetStarted: 'Get Started',
  cookiePolicyTitle: 'Cookie Policy & Consent',
  docHeaderTitle: '8D REPORT',
  docHeaderSub: 'Problem Solving',
  docD1: 'Team',
  docD2: 'Description',
  docD4: 'Root Cause',
  docD5D8: 'Actions',
  metaTitle: '8D Generator | IATF Solutions',
  metaDescription: 'Your IATF-compliant 8D report in minutes. Structured problem-solving per IATF 16949.'
}

export const eightdInfoSeedDataDe = {
  heroBadge: '8D GENERATOR',
  backToHome: 'Zurück zur Übersicht',
  heroTitle: 'Ihr IATF-konformer',
  heroTitleHighlight: '8D-Bericht in Minuten',
  heroDescription: 'Strukturierte Problemlösung nach IATF 16949 — kein Excel-Chaos, keine Vorlagensuche. Felder ausfüllen, KI generiert, PDF und Excel laden.',
  ctaCredits: 'Credits kaufen',
  ctaBuy: 'Credits kaufen',
  ctaSample: 'Beispiel laden',
  sampleDownload: 'Beispiel laden (PDF)',
  sampleCta: 'Jetzt Bericht erstellen',
  sampleLabel: 'BEISPIELAUSGABE',
  sampleTitle: 'Professionelle 8D-Ausgabe',
  sampleDesc: 'Laden Sie unseren Beispielbericht herunter, um zu sehen, wie wir Problembeschreibung, Ursachenanalyse und Korrekturmaßnahmen strukturieren.',
  trust1: 'IATF 16949 konform',
  trust2: 'Audit-fähiger Export',
  trust3: 'KI-geführte Analyse',
  trust4: 'PDF & Excel Ausgabe',
  trust5: 'Kein Abonnement',
  outputLabel: 'PROFESSIONELLE AUSGABE',
  outputBadge: 'INKLUSIVE',
  outputPdfTitle: 'Offizieller 8D-PDF-Bericht',
  outputPdfDesc: 'Ein formatiertes PDF-Dokument, bereit für den Versand an Ihre Kunden oder Auditoren.',
  outputExcelTitle: 'Excel-Datei für Daten',
  outputExcelDesc: 'Ihre 8D-Daten in einem sauberen Excel-Format für internes Tracking und Analysen.',
  disciplinesLabel: 'KERNKOMPETENZEN',
  disciplinesTitle: 'Alle acht Disziplinen abgedeckt',
  disciplinesSub: 'Der Generator führt Sie durch jede Disziplin und stellt sicher, dass kein Pflichtfeld fehlt — genau wie Auditoren es fordern.',
  d1Title: 'D1 Team',
  d1Desc: 'Definieren Sie Ihr Team und weisen Sie Rollen für die Untersuchung zu.',
  d2Title: 'D2 Problembeschreibung',
  d2Desc: 'Strukturierte Beschreibung mittels 5W2H-Methodik für maximale Klarheit.',
  d3Title: 'D3 Sofortmaßnahmen',
  d3Desc: 'Dokumentieren Sie Maßnahmen zum Schutz des Kunden vor weiteren Fehlern.',
  d4Title: 'D4 Ursachenanalyse',
  d4Desc: 'KI-unterstützte 5-Why-Analyse zur Identifizierung der technischen und systemischen Ursachen.',
  d5Title: 'D5 Korrekturmaßnahmen',
  d5Desc: 'Legen Sie dauerhafte Maßnahmen fest, um die Ursache endgültig abzustellen.',
  d6Title: 'D6 Wirksamkeit',
  d6Desc: 'Verfolgen Sie den Status Ihrer Maßnahmen und dokumentieren Sie deren Umsetzung.',
  d7Title: 'D7 Vorbeugemaßnahmen',
  d7Desc: 'Aktualisieren Sie FMEA und Control Plans, um Wiederholungsfehler zu vermeiden.',
  d8Title: 'D8 Abschluss',
  d8Desc: 'Schließen Sie den Bericht mit der Anerkennung der Teamleistung ab.',
  howLabel: 'EINFACHER PROZESS',
  howTitle: 'In 3 Schritten zum fertigen Bericht',
  step1Title: 'Zugangscode',
  step1Desc: 'Geben Sie Ihren Code ein — kein Account oder Registrierung zum Start erforderlich.',
  step2Title: 'Felder ausfüllen',
  step2Desc: 'Nutzen Sie den geführten Wizard Schritt für Schritt mit unserer intelligenten Hilfe.',
  step3Title: 'Download',
  step3Desc: 'Laden Sie Ihren audit-fähigen PDF und Excel Bericht sofort herunter.',
  pricingLabel: 'TRANSPARENTE PREISE',
  pricingTitle: 'Einfacher Credit-basierter Zugang',
  pricingSub: 'Ein Credit pro fertigem 8D-Bericht.',
  popularBadge: 'AM BELIEBTESTEN',
  plan1Credits: '1 CREDIT',
  plan1Price: '299',
  plan1Per: 'pro 8D-Bericht',
  plan1Feature1: 'Alle 8D-Disziplinen',
  plan1Feature2: 'KI-gestützte Analyse',
  plan1Feature3: 'Excel & PDF Export',
  plan1Feature4: '24h Sitzungszugriff',
  plan2Credits: '5er PACK',
  plan2Price: '1199',
  plan2Per: 'für 5 Berichte',
  plan2Feature1: '5 Generierungen',
  plan2Feature2: 'Am beliebtesten',
  plan2Feature3: 'Bester Wert',
  plan3Credits: '20er PACK',
  plan3Price: 'Auf Anfrage',
  plan3Per: 'Individuelle Preise',
  plan3Feature1: '20 Generierungen',
  plan3Feature2: 'Mengenrabatt',
  plan3Feature3: 'Für Teams',
  pricingNote: 'Preise in EUR zzgl. MwSt. falls zutreffend. Sofortige Credit-Lieferung.',
  faqLabel: 'HÄUFIG GESTELLTE FRAGEN',
  faq1Q: 'Benötige ich einen Account?',
  faq1A: 'Nein. Wir nutzen ein einfaches Zugangscode-System. Sie können sofort nach dem Kauf starten.',
  faq2Q: 'Welche Sprachen werden unterstützt?',
  faq2A: 'Das Interface und die Berichte sind auf Englisch und Deutsch verfügbar. Sie können jederzeit wechseln.',
  faq3Q: 'Wie lange habe ich Zugriff auf den Bericht?',
  faq3A: 'Nach Eingabe des Codes ist Ihre Sitzung für 24 Stunden aktiv. In dieser Zeit können Sie die Dateien beliebig oft laden.',
  faq4Q: 'Werden meine Daten zum KI-Training genutzt?',
  faq4A: 'Nein. Ihre Daten werden sicher verarbeitet und niemals zum Training unserer KI-Modelle verwendet.',
  faq5Q: 'Was passiert, wenn ich später ein Update brauche?',
  faq5A: 'Ein Credit deckt eine Sitzung ab. Für spätere große Änderungen nach Ablauf der 24h ist ein neuer Credit nötig.',
  finalCtaTitle: 'Bereit für Ihren ersten Bericht?',
  finalCtaDesc: 'Schließen Sie sich Qualitätsmanagern an, die ihre 8D-Berichte automatisiert haben.',
  finalCtaBuy: 'Credits kaufen',
  finalCtaGetStarted: 'Jetzt starten',
  cookiePolicyTitle: 'Cookie-Richtlinie & Einwilligung',
  docHeaderTitle: '8D BERICHT',
  docHeaderSub: 'Problemlösung',
  docD1: 'Team',
  docD2: 'Beschreibung',
  docD4: 'Ursache',
  docD5D8: 'Maßnahmen',
  metaTitle: '8D Generator | IATF Solutions',
  metaDescription: 'Ihr IATF-konformer 8D-Bericht in Minuten. Strukturierte Problemlösung nach IATF 16949.'
}

export const fmeaInfoSeedDataEn = {
  heroBadge: 'AIAG/VDA FMEA REVIEW',
  backToHome: 'Back to Home',
  heroTitle: 'Your FMEA review',
  heroTitleHighlight: 'in minutes — not days',
  heroDescription: 'Upload your existing FMEA. The system automatically checks it against AIAG/VDA 5th Edition, validates every Action Priority value, and delivers a structured PDF report.',
  ctaCredits: 'Buy credits',
  ctaBuy: 'Buy Credits',
  ctaSample: 'Download Sample',
  sampleDownload: 'Download Sample (PDF)',
  sampleCta: 'Analyze Yours Now',
  sampleLabel: 'SAMPLE REPORT',
  sampleTitle: 'See the Analysis Quality',
  sampleDesc: 'Download our comprehensive FMEA review sample report to see how we identify gaps, validate AP logic, and provide actionable improvement recommendations.',
  trust1: 'AIAG/VDA 5th Ed. Compliant',
  trust2: 'Automatic AP Validation',
  trust3: 'No Manual Analysis',
  trust4: 'PDF Summary Export',
  trust5: 'Secure File Handling',
  outputLabel: 'PROFESSIONAL OUTPUT',
  outputBadge: 'INCLUDED',
  outputPdfTitle: 'FMEA Review Report',
  outputPdfDesc: 'A detailed PDF summary of all findings, scoring your FMEA against industry standards.',
  outputExcelTitle: 'Annotated Workbook',
  outputExcelDesc: 'Your original data with embedded comments and warnings for every identified issue.',
  disciplinesLabel: 'CORE CAPABILITIES',
  disciplinesTitle: 'Smart checks for complex workbooks',
  disciplinesSub: 'Our system analyzes every row of your FMEA to ensure compliance and identify hidden risks.',
  d1Title: 'Structure Check',
  d1Desc: 'Ensures the logical link between functions, failures, effects, and causes is consistent.',
  d2Title: 'AP Validation',
  d2Desc: 'Automatically recalculates Action Priority (AP) based on S, O, and D to find errors.',
  d3Title: 'Completeness Score',
  d3Desc: 'Identifies missing preventive or detective controls across all failure modes.',
  d4Title: 'Severity Mapping',
  d4Desc: 'Checks if failure effects are consistently rated across the entire document.',
  d5Title: 'Recommendation Logic',
  d5Desc: 'Provides smart suggestions for improvement where AP is High or Medium.',
  d6Title: 'Fast Processing',
  d6Desc: 'Analyze workbooks with thousands of rows in seconds, not hours.',
  howLabel: 'SIMPLE PROCESS',
  howTitle: 'From Upload to Export in 3 Steps',
  step1Title: 'Upload FMEA',
  step1Desc: 'Upload your Excel or CSV file. We support all common AIAG/VDA templates.',
  step2Title: 'Review Findings',
  step2Desc: 'Our AI analyzes the content and highlights gaps and logic errors instantly.',
  step3Title: 'Export Evidence',
  step3Desc: 'Download your professional review report as a PDF for your audit trail.',
  pricingLabel: 'TRANSPARENT PRICING',
  pricingTitle: 'Pay per FMEA analysis',
  pricingSub: 'One credit per FMEA workbook review.',
  popularBadge: 'MOST POPULAR',
  plan1Credits: '1 CREDIT',
  plan1Price: '299',
  plan1Per: 'per FMEA Workbook',
  plan1Feature1: 'Full AIAG/VDA Check',
  plan1Feature2: 'AP Logic Validation',
  plan1Feature3: 'PDF Review Report',
  plan1Feature4: '24h Session Access',
  plan2Credits: '5 PACK',
  plan2Price: '1199',
  plan2Per: 'per 5 Workbooks',
  plan2Feature1: '5 generations',
  plan2Feature2: 'Most popular',
  plan2Feature3: 'Best value',
  plan3Credits: '20 PACK',
  plan3Price: 'On request',
  plan3Per: 'Custom pricing',
  plan3Feature1: '20 generations',
  plan3Feature2: 'Bulk deal',
  plan3Feature3: 'For teams',
  pricingNote: 'Prices in EUR plus VAT where applicable. Instant credit delivery.',
  faqLabel: 'FREQUENTLY ASKED QUESTIONS',
  faq1Q: 'Which FMEA formats are supported?',
  faq1A: 'We support Excel (.xlsx) and CSV files. Our parser is trained on common industry templates from AIAG/VDA 5th edition.',
  faq2Q: 'Does the system calculate AP automatically?',
  faq2A: 'Yes. We validate your entered Action Priority against the tables for Severity, Occurrence, and Detection.',
  faq3Q: 'Is my data secure?',
  faq3A: 'Absolutely. Files are processed in memory and are never used for AI training. Data is deleted after your session expires.',
  faq4Q: 'What is the "Completeness Score"?',
  faq4A: 'It measures how many of your failure modes have defined controls and actions compared to industry best practices.',
  faq5Q: 'Can I analyze large workbooks?',
  faq5A: 'Yes. Our system is optimized for industrial-scale FMEAs with thousands of rows.',
  faq6Q: 'Do I need a subscription?',
  faq6A: 'No. You buy credits and use them when you need to review a document. No recurring fees.',
  finalCtaTitle: 'Ready to master your FMEAs?',
  finalCtaDesc: 'Join quality engineers who use our AI to catch errors before the audit starts.',
  finalCtaBuy: 'Buy Credits',
  finalCtaGetStarted: 'Get Started',
  cookiePolicyTitle: 'Cookie Policy & Consent',
  docHeaderTitle: 'FMEA REVIEW',
  docHeaderSub: 'Quality Analysis',
  docD1: 'Structure',
  docD2: 'Logic (AP)',
  docD4: 'Severity',
  docD5D8: 'Actions',
  metaTitle: 'FMEA Reviewer | IATF Solutions',
  metaDescription: 'Your FMEA review in minutes. Automatic AIAG/VDA compliance checks and AP validation.'
}

export const fmeaInfoSeedDataDe = {
  heroBadge: 'AIAG/VDA FMEA PRÜFUNG',
  backToHome: 'Zurück zur Übersicht',
  heroTitle: 'Ihre FMEA-Prüfung',
  heroTitleHighlight: 'in Minuten — nicht Tagen',
  heroDescription: 'Laden Sie Ihre bestehende FMEA hoch. Das System prüft sie automatisch gegen die AIAG/VDA 5. Ausgabe und liefert einen strukturierten PDF-Bericht.',
  ctaCredits: 'Credits kaufen',
  ctaBuy: 'Credits kaufen',
  ctaSample: 'Beispiel laden',
  sampleDownload: 'Beispiel laden (PDF)',
  sampleCta: 'Jetzt prüfen',
  sampleLabel: 'BEISPIELAUSGABE',
  sampleTitle: 'Qualität der Analyse',
  sampleDesc: 'Laden Sie unseren Beispielbericht herunter, um zu sehen, wie wir Lücken identifizieren, die AP-Logik validieren und Verbesserungen vorschlagen.',
  trust1: 'AIAG/VDA 5. Ausg. konform',
  trust2: 'Automatische AP-Prüfung',
  trust3: 'Keine manuelle Analyse',
  trust4: 'PDF-Zusammenfassung',
  trust5: 'Sicherer Dateitransfer',
  outputLabel: 'PROFESSIONELLE AUSGABE',
  outputBadge: 'INKLUSIVE',
  outputPdfTitle: 'FMEA-Review-Bericht',
  outputPdfDesc: 'Eine detaillierte PDF-Zusammenfassung aller Befunde, die Ihre FMEA gegen Industriestandards bewertet.',
  outputExcelTitle: 'Kommentierte Datei',
  outputExcelDesc: 'Ihre Originaldaten mit eingebetteten Kommentaren und Warnungen für jeden gefundenen Fehler.',
  disciplinesLabel: 'KERNKOMPETENZEN',
  disciplinesTitle: 'Intelligente Prüfung für komplexe Dateien',
  disciplinesSub: 'Unser System analysiert jede Zeile Ihrer FMEA, um Compliance sicherzustellen und Risiken zu finden.',
  d1Title: 'Strukturprüfung',
  d1Desc: 'Stellt sicher, dass die logische Verknüpfung zwischen Funktionen, Fehlern und Ursachen konsistent ist.',
  d2Title: 'AP-Validierung',
  d2Desc: 'Berechnet die Aufgabenpriorität (AP) basierend auf S, O und D automatisch neu, um Fehler zu finden.',
  d3Title: 'Vollständigkeit',
  d3Desc: 'Identifiziert fehlende Vermeidungs- oder Entdeckungsmaßnahmen über alle Fehlermöglichkeiten hinweg.',
  d4Title: 'Bedeutungs-Check',
  d4Desc: 'Prüft, ob Fehlerfolgen über das gesamte Dokument hinweg einheitlich bewertet wurden.',
  d5Title: 'Verbesserungsvorschläge',
  d5Desc: 'Bietet intelligente Vorschläge für Maßnahmen, wo die AP auf Hoch oder Mittel steht.',
  d6Title: 'Schnelle Verarbeitung',
  d6Desc: 'Analysieren Sie Workbooks mit tausenden Zeilen in Sekunden, nicht Stunden.',
  howLabel: 'EINFACHER PROZESS',
  howTitle: 'In 3 Schritten zum Review',
  step1Title: 'FMEA hochladen',
  step1Desc: 'Laden Sie Ihre Excel- oder CSV-Datei hoch. Wir unterstützen alle gängigen AIAG/VDA Vorlagen.',
  step2Title: 'Befunde prüfen',
  step2Desc: 'Unsere KI analysiert den Inhalt und markiert Lücken und Logikfehler sofort.',
  step3Title: 'Nachweis exportieren',
  step3Desc: 'Laden Sie Ihren Review-Bericht als PDF für Ihren Audit-Trail herunter.',
  pricingLabel: 'TRANSPARENTE PREISE',
  pricingTitle: 'Zahlen Sie pro FMEA-Prüfung',
  pricingSub: 'Ein Credit pro FMEA-Workbook-Review.',
  popularBadge: 'AM BELIEBTESTEN',
  plan1Credits: '1 CREDIT',
  plan1Price: '299',
  plan1Per: 'pro FMEA-Datei',
  plan1Feature1: 'Voller AIAG/VDA Check',
  plan1Feature2: 'AP-Logik Validierung',
  plan1Feature3: 'PDF-Review-Bericht',
  plan1Feature4: '24h Sitzungszugriff',
  plan2Credits: '5er PACK',
  plan2Price: '1199',
  plan2Per: 'für 5 Dateien',
  plan2Feature1: '5 Generierungen',
  plan2Feature2: 'Am beliebtesten',
  plan2Feature3: 'Bester Wert',
  plan3Credits: '20er PACK',
  plan3Price: 'Auf Anfrage',
  plan3Per: 'Individuelle Preise',
  plan3Feature1: '20 Generierungen',
  plan3Feature2: 'Mengenrabatt',
  plan3Feature3: 'Für Teams',
  pricingNote: 'Preise in EUR zzgl. MwSt. falls zutreffend. Sofortige Credit-Lieferung.',
  faqLabel: 'HÄUFIG GESTELLTE FRAGEN',
  faq1Q: 'Welche Formate werden unterstützt?',
  faq1A: 'Wir unterstützen Excel (.xlsx) und CSV. Unser Parser kennt die gängigen AIAG/VDA Vorlagen.',
  faq2Q: 'Wird die AP automatisch berechnet?',
  faq2A: 'Ja. Wir validieren Ihre Priorität gegen die offiziellen Tabellen für S, O und D.',
  faq3Q: 'Sind meine Daten sicher?',
  faq3A: 'Absolut. Dateien werden im Speicher verarbeitet und nicht für KI-Training genutzt. Löschung nach 24h.',
  faq4Q: 'Was ist der "Vollständigkeits-Score"?',
  faq4A: 'Er misst, wie viele Ihrer Fehlermöglichkeiten definierte Maßnahmen gemäß Best Practices haben.',
  faq5Q: 'Gehen auch große Dateien?',
  faq5A: 'Ja. Unser System ist für industrielle FMEAs mit tausenden Zeilen optimiert.',
  faq6Q: 'Brauche ich ein Abo?',
  faq6A: 'Nein. Sie kaufen Credits bei Bedarf. Keine monatlichen Fixkosten.',
  finalCtaTitle: 'Bereit, Ihre FMEAs zu beherrschen?',
  finalCtaDesc: 'Schließen Sie sich Ingenieuren an, die unsere KI nutzen, um Fehler vor dem Audit zu finden.',
  finalCtaBuy: 'Credits kaufen',
  finalCtaGetStarted: 'Jetzt starten',
  cookiePolicyTitle: 'Cookie-Richtlinie & Einwilligung',
  docHeaderTitle: 'FMEA REVIEW',
  docHeaderSub: 'Qualitätsanalyse',
  docD1: 'Struktur',
  docD2: 'Logik (AP)',
  docD4: 'Bedeutung',
  docD5D8: 'Maßnahmen',
  metaTitle: 'FMEA Reviewer | IATF Solutions',
  metaDescription: 'Ihre FMEA-Prüfung in Minuten. Automatische AIAG/VDA Compliance-Prüfungen und AP-Validierung.'
}
