import { NextRequest, NextResponse } from 'next/server'
import { isAuthenticatedFromRequest } from '@/lib/session/session'
import type { MatrixRow, ProcessEntry, ConflictInfo, ImplementationRecord, ImplementationStatus } from '@/modules/csr/types'

export const runtime = 'nodejs'
export const maxDuration = 60

/* ─── Request schema ────────────────────────────────────────────── */

interface PdfExportRequest {
  matrixRows: MatrixRow[]
  processes: ProcessEntry[]
  selectedOems: string[]
  companyName?: string
  companyLocation?: string
  language: 'de' | 'en'
  conflicts?: ConflictInfo[]
  implementationRecords?: Record<string, ImplementationRecord>
  companyLogo?: string
  processMapImage?: string
}

/* ─── Labels ────────────────────────────────────────────────────── */

const LABELS = {
  en: {
    title: 'Customer-Specific Requirements Matrix',
    summaryTitle: 'Executive Summary',
    generated: 'Generated',
    company: 'Company',
    location: 'Location',
    oems: 'OEMs',
    totalReqs: 'Total Requirements',
    oemReqs: 'OEM-Specific',
    baseReqs: 'IATF Base',
    conflictsCount: 'Conflicts',
    chapter: 'Chapter',
    requirement: 'Requirement',
    description: 'Description',
    oem: 'OEM / Source',
    risk: 'Risk',
    severity: 'Severity',
    version: 'Version',
    changeStatus: 'Change Status',
    sourceDoc: 'Source Document',
    implStatus: 'Impl. Status',
    processOwner: 'Process Owner',
    dueDate: 'Due Date',
    evidence: 'Evidence',
    processes: 'Processes',
    conflictSection: 'Overlaps & Conflicts',
    riskBreakdown: 'Risk Breakdown',
    implBreakdown: 'Implementation Status',
    processMapSection: 'Process Map',
    oemSectionPrefix: 'Requirements:',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    implOpen: 'Open',
    implInReview: 'In Review',
    implImplemented: 'Implemented',
    implValidated: 'Validated',
    sevSupp: 'Supplementary',
    sevTight: 'Tightening',
    sevRepl: 'Replacing',
    new: 'New',
    updated: 'Updated',
    unchanged: 'Unchanged',
    deleted: 'Deleted',
    active: 'Active',
    outdated: 'Outdated',
    conflictDecision: 'Recommendation: Apply stricter requirement and document rationale.',
    disclaimer: 'This report was generated by IATF Solutions CSR Matrix Tool. Always verify against the latest OEM source documents.',
    page: 'Page',
    noConflicts: 'No conflicts detected.',
    decisionRule: 'Conflict Recommendation Rule',
    decisionRuleVal: 'Most stringent CSR requirement should be applied where OEM requirements overlap.',
    reason: 'Reason',
  },
  de: {
    title: 'Kundenspezifische Anforderungsmatrix',
    summaryTitle: 'Zusammenfassung',
    generated: 'Erstellt',
    company: 'Unternehmen',
    location: 'Standort',
    oems: 'OEMs',
    totalReqs: 'Anforderungen gesamt',
    oemReqs: 'OEM-spezifisch',
    baseReqs: 'IATF Basis',
    conflictsCount: 'Konflikte',
    chapter: 'Kapitel',
    requirement: 'Anforderung',
    description: 'Beschreibung',
    oem: 'OEM / Quelle',
    risk: 'Risiko',
    severity: 'Schweregrad',
    version: 'Version',
    changeStatus: 'Änderungsstatus',
    sourceDoc: 'Quelldokument',
    implStatus: 'Umset.-Status',
    processOwner: 'Prozessverantwortlicher',
    dueDate: 'Fälligkeitsdatum',
    evidence: 'Nachweis',
    processes: 'Prozesse',
    conflictSection: 'Überschneidungen & Konflikte',
    riskBreakdown: 'Risikoverteilung',
    implBreakdown: 'Umsetzungsstatus',
    processMapSection: 'Prozesslandkarte',
    oemSectionPrefix: 'Anforderungen:',
    critical: 'Kritisch',
    high: 'Hoch',
    medium: 'Mittel',
    low: 'Niedrig',
    implOpen: 'Offen',
    implInReview: 'In Prüfung',
    implImplemented: 'Umgesetzt',
    implValidated: 'Validiert',
    sevSupp: 'Ergänzend',
    sevTight: 'Verschärfend',
    sevRepl: 'Ersetzend',
    new: 'Neu',
    updated: 'Aktualisiert',
    unchanged: 'Unverändert',
    deleted: 'Entfernt',
    active: 'Aktiv',
    outdated: 'Veraltet',
    conflictDecision: 'Empfehlung: Strengere Anforderung anwenden und Begründung dokumentieren.',
    disclaimer: 'Dieser Bericht wurde mit dem IATF Solutions CSR Matrix Tool erstellt. Bitte stets mit den aktuellen OEM-Quelldokumenten abgleichen.',
    page: 'Seite',
    noConflicts: 'Keine Konflikte erkannt.',
    decisionRule: 'Konflikt-Empfehlungsregel',
    decisionRuleVal: 'Bei überlappenden OEM-Anforderungen gilt die jeweils strengste CSR-Anforderung.',
    reason: 'Begründung',
  },
} as const

type Labels = (typeof LABELS)[keyof typeof LABELS]

/* ─── Helpers ───────────────────────────────────────────────────── */

const BRAND_COLOR = '#1d4ed8'
const BRAND_COLOR_DARK = '#1e3a5f'
const PAGE_W = 595  // A4 width in points
const MARGIN = 40
const CONTENT_W = PAGE_W - MARGIN * 2

function riskColor(risk: string) {
  return risk === 'critical' ? '#dc2626'
    : risk === 'high' ? '#ea580c'
      : risk === 'medium' ? '#ca8a04'
        : '#16a34a'
}

function riskBg(risk: string) {
  return risk === 'critical' ? '#FEE2E2'
    : risk === 'high' ? '#FFEDD5'
      : risk === 'medium' ? '#FEF9C3'
        : '#DCFCE7'
}

function implLabel(status: ImplementationStatus | undefined, L: Labels) {
  if (!status || status === 'open') return L.implOpen
  if (status === 'in_review') return L.implInReview
  if (status === 'implemented') return L.implImplemented
  if (status === 'validated') return L.implValidated
  return L.implOpen
}

function severityLabel(sev: string | null | undefined, L: Labels) {
  if (!sev) return '—'
  return sev === 'tightening' ? L.sevTight
    : sev === 'replacing' ? L.sevRepl
      : L.sevSupp
}

function changeLabel(status: string, L: Labels) {
  return status === 'new' ? L.new
    : status === 'updated' ? L.updated
      : status === 'deleted' ? L.deleted
        : L.unchanged
}

function sortByChapter(rows: MatrixRow[]) {
  return [...rows].sort((a, b) =>
    a.iatfChapter.localeCompare(b.iatfChapter, undefined, { numeric: true }),
  )
}

/* ─── Route handler ─────────────────────────────────────────────── */

export async function POST(request: NextRequest) {
  const authed = await isAuthenticatedFromRequest(request)
  if (!authed) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body: PdfExportRequest
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const {
    matrixRows,
    processes,
    selectedOems,
    companyName,
    companyLocation,
    language,
    conflicts = [],
    implementationRecords = {},
    companyLogo,
    processMapImage,
  } = body

  if (!matrixRows || !Array.isArray(matrixRows) || matrixRows.length === 0) {
    return NextResponse.json({ error: 'No matrix data' }, { status: 400 })
  }

  const L = LABELS[language] ?? LABELS.en

  try {
    const PDFDocument = (await import('pdfkit')).default
    const chunks: Buffer[] = []
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 60, left: MARGIN, right: MARGIN },
      info: {
        Title: L.title,
        Author: 'IATF Solutions',
        Creator: 'CSR Matrix Generator',
      },
      autoFirstPage: false,
    })

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    const finished = new Promise<void>((resolve) => doc.on('end', resolve))

    let pageNum = 0

    /* ── Page footer helper ────────────────────────────────────────── */
    function drawFooter() {
      const oldX = doc.x, oldY = doc.y;
      const oldMarginBottom = doc.page.margins.bottom;
      
      // Temporarily remove the bottom margin so PDFKit doesn't auto-paginate
      // the footer text, which would cause an infinite recursion loop!
      doc.page.margins.bottom = 0;
      
      const footerY = doc.page.height - 35
      doc.save()
      doc.fontSize(7).fillColor('#94a3b8').font('Helvetica')
      doc.text(`${L.title}`, MARGIN, footerY, { width: CONTENT_W * 0.6, align: 'left', lineBreak: false })
      doc.text(`${L.page} ${pageNum}`, MARGIN, footerY, { width: CONTENT_W, align: 'right', lineBreak: false })
      doc.restore()
      
      doc.page.margins.bottom = oldMarginBottom;
      doc.x = oldX
      doc.y = oldY
    }

    doc.on('pageAdded', () => {
      pageNum++
      drawFooter()
    })

    function newPage() {
      // The addPage call triggers 'pageAdded' which increments pageNum and draws footer
      doc.addPage()
    }

    /* ── Section header helper ─────────────────────────────────────── */
    function sectionHeader(text: string, color = BRAND_COLOR) {
      if (doc.y > 680) newPage()
      doc.rect(MARGIN, doc.y, CONTENT_W, 20).fill(color)
      const oldY = doc.y
      doc.fontSize(11).fillColor('#ffffff').font('Helvetica-Bold')
        .text(text, MARGIN + 6, oldY + 5, { width: CONTENT_W - 12 })
      doc.y = oldY + 28
    }

    /* ── Statistics ─────────────────────────────────────────────────── */
    const sorted = sortByChapter(matrixRows)
    const baseRows = matrixRows.filter((r) => r.oem === 'IATF 16949')
    const oemRows = matrixRows.filter((r) => r.oem !== 'IATF 16949')
    const byRisk = { low: 0, medium: 0, high: 0, critical: 0 }
    const byImpl = { open: 0, in_review: 0, implemented: 0, validated: 0 }

    for (const row of matrixRows) {
      byRisk[row.risk]++
      const impl = implementationRecords[row.csrId]
      byImpl[impl?.status ?? 'open']++
    }

    /* ================================================================ */
    /*  COVER PAGE                                                       */
    /* ================================================================ */
    newPage()

    // Logo
    if (companyLogo) {
      try {
        const match = companyLogo.match(/^data:image\/[^;]+;base64,(.+)$/)
        if (match) {
          const buf = Buffer.from(match[1], 'base64')
          doc.image(buf, MARGIN, MARGIN, { width: 150, height: 45, fit: [150, 45] })
        }
      } catch { /* skip broken logo */ }
    }

    // IATF Solutions brand top-right
    doc.fontSize(8).fillColor('#94a3b8').font('Helvetica')
      .text('IATF Solutions', MARGIN, MARGIN + 5, { width: CONTENT_W, align: 'right' })

    // Title block
    const titleY = companyLogo ? 120 : 90
    doc.rect(MARGIN, titleY, CONTENT_W, 56).fill(BRAND_COLOR)
    doc.fontSize(18).fillColor('#ffffff').font('Helvetica-Bold')
      .text(L.title, MARGIN + 12, titleY + 10, { width: CONTENT_W - 24, align: 'center' })
    doc.fontSize(10).fillColor('#bfdbfe').font('Helvetica')
      .text(L.summaryTitle, MARGIN + 12, titleY + 36, { width: CONTENT_W - 24, align: 'center' })

    doc.y = titleY + 76

    doc.moveDown(1)
    const uniqueOwners = Array.from(new Set([
      ...Object.values(implementationRecords || {})
        .map(r => r.processOwner || r.assignee)
        .filter(Boolean),
      ...(processes || []).map(p => p.owner).filter(Boolean)
    ])) as string[]
    const processOwnersStr = uniqueOwners.length > 0 ? uniqueOwners.join(', ') : '—'

    const meta: [string, string][] = [
      [L.generated, new Date().toLocaleDateString(language === 'de' ? 'de-DE' : 'en-GB')],
      [L.company, companyName || '—'],
      [L.location, companyLocation || '—'],
      [L.oems, selectedOems.join(', ')],
      [L.processOwner, processOwnersStr],
    ]
    doc.fontSize(10).fillColor('#334155')
    for (const [label, val] of meta) {
      doc.font('Helvetica-Bold').text(`${label}: `, { continued: true })
      doc.font('Helvetica').text(val)
    }
    doc.moveDown(1.5)

    // Stats grid
    const statItems: [string, number, string][] = [
      [L.totalReqs, matrixRows.length, '#1d4ed8'],
      [L.baseReqs, baseRows.length, '#0369a1'],
      [L.oemReqs, oemRows.length, '#7c3aed'],
      [L.conflictsCount, conflicts.length, '#b45309'],
    ]
    const cellW = CONTENT_W / 4
    const statY = doc.y
    for (let i = 0; i < statItems.length; i++) {
      const [label, count, color] = statItems[i]
      const x = MARGIN + i * cellW
      doc.rect(x, statY, cellW - 4, 52).fill('#f8fafc')
      doc.fontSize(22).fillColor(color).font('Helvetica-Bold')
        .text(String(count), x + 4, statY + 6, { width: cellW - 8, align: 'center' })
      doc.fontSize(8).fillColor('#64748b').font('Helvetica')
        .text(label, x + 4, statY + 34, { width: cellW - 8, align: 'center' })
    }
    doc.y = statY + 62

    doc.moveDown(1)

    // Risk breakdown bar
    sectionHeader(L.riskBreakdown)
    const riskItems: [string, number, string][] = [
      [L.critical, byRisk.critical, '#dc2626'],
      [L.high, byRisk.high, '#ea580c'],
      [L.medium, byRisk.medium, '#ca8a04'],
      [L.low, byRisk.low, '#16a34a'],
    ]
    doc.fontSize(8).font('Helvetica')
    for (const [label, count, color] of riskItems) {
      const pct = matrixRows.length > 0 ? count / matrixRows.length : 0
      const barW = Math.max(pct * (CONTENT_W - 100), 2)
      const currentY = doc.y

      doc.fillColor(color).rect(MARGIN, currentY, barW, 10).fill()
      doc.fillColor('#334155').text(`${label}: ${count}`, MARGIN + barW + 6, currentY + 1, { width: 80 })
      
      doc.y = currentY + 16
    }


    /* ================================================================ */
    /*  PROCESS MAP PAGE (if provided)                                   */
    /* ================================================================ */
    if (processMapImage) {
      try {
        const match = processMapImage.match(/^data:image\/[^;]+;base64,(.+)$/)
        if (match) {
          newPage()
          sectionHeader(L.processMapSection)
          const buf = Buffer.from(match[1], 'base64')
          const imgMaxH = 480
          const imgY = doc.y
          doc.image(buf, MARGIN, imgY, { width: CONTENT_W, height: imgMaxH, fit: [CONTENT_W, imgMaxH] })
        }
      } catch { /* skip broken image */ }
    }

    /* ================================================================ */
    /*  FULL REQUIREMENTS TABLE (all OEMs combined)                      */
    /* ================================================================ */
    newPage()
    sectionHeader(L.title)

    // Table columns: Chapter | Requirement | OEM | Risk | Severity | Processes
    const colX = [MARGIN, MARGIN + 55, MARGIN + 185, MARGIN + 250, MARGIN + 300, MARGIN + 370]
    const colW = [53, 128, 63, 48, 68, 145]
    const hdrs = [L.chapter, L.requirement, L.oem, L.risk, L.severity, L.processes]

    function drawTableHeader() {
      doc.rect(MARGIN, doc.y - 2, CONTENT_W, 16).fill(BRAND_COLOR)
      const y = doc.y
      doc.fillColor('#ffffff').fontSize(7).font('Helvetica-Bold')
      for (let i = 0; i < hdrs.length; i++) {
        doc.text(hdrs[i], colX[i], y, { width: colW[i], align: 'left' })
      }
      doc.y = y + 18
      doc.fillColor('#334155').font('Helvetica')
    }

    drawTableHeader()

    for (let i = 0; i < sorted.length; i++) {
      const mr = sorted[i]
      const impl = implementationRecords[mr.csrId]
      const chapterStr = mr.iatfChapter + (mr.conflictFlag ? ' ⚠' : '')
      const titleStr = mr.title
      const oemStr = mr.oem === 'IATF 16949' ? 'IATF' : mr.oem
      const riskStr = mr.risk.charAt(0).toUpperCase() + mr.risk.slice(1)
      const sevStr = severityLabel(mr.severity, L)
      const processNames = mr.affectedProcessIds.length > 0
        ? mr.affectedProcessIds.map((pid) => {
          const p = processes?.find((pr) => pr.id === pid)
          return p?.name ?? pid
        }).join(', ')
        : '—'

      doc.fontSize(6.5).font('Helvetica')
      const rowH = Math.max(
        doc.heightOfString(chapterStr, { width: colW[0] }),
        doc.heightOfString(titleStr, { width: colW[1] }),
        doc.heightOfString(oemStr, { width: colW[2] }),
        doc.heightOfString(riskStr, { width: colW[3] }),
        doc.heightOfString(sevStr, { width: colW[4] }),
        doc.heightOfString(processNames, { width: colW[5] }),
      ) + 4

      if (doc.y + rowH > 730) {
        newPage()
        drawTableHeader()
      }

      const y = doc.y
      if (i % 2 === 1) doc.rect(MARGIN, y - 1, CONTENT_W, rowH).fill('#f8fafc')
      doc.fillColor('#334155')
        .text(chapterStr, colX[0], y, { width: colW[0] })
        .text(titleStr, colX[1], y, { width: colW[1] })
        .text(oemStr, colX[2], y, { width: colW[2] })
      doc.fillColor(riskColor(mr.risk)).text(riskStr, colX[3], y, { width: colW[3] })
      doc.fillColor('#334155')
        .text(sevStr, colX[4], y, { width: colW[4] })
        .text(processNames, colX[5], y, { width: colW[5] })
      doc.y = y + rowH
    }

    /* ================================================================ */
    /*  PER-OEM DETAILED SECTIONS                                        */
    /* ================================================================ */
    for (const oem of selectedOems) {
      const oemSpecific = sorted.filter((r) => r.oem === oem)
      if (oemSpecific.length === 0) continue

      newPage()
      sectionHeader(`${oem} — ${L.oemSectionPrefix}`, BRAND_COLOR_DARK)

      for (let i = 0; i < oemSpecific.length; i++) {
        const mr = oemSpecific[i]
        const impl = implementationRecords[mr.csrId]

        // Only check if we have enough space for the header of the block
        if (doc.y > 700) newPage()

        const blockY = doc.y

        // Chapter badge
        doc.rect(MARGIN, blockY, 50, 13).fill(riskBg(mr.risk))
        doc.fontSize(7).fillColor(riskColor(mr.risk)).font('Helvetica-Bold')
          .text(mr.iatfChapter, MARGIN + 2, blockY + 2, { width: 46 })

        // Conflict flag
        if (mr.conflictFlag) {
          doc.fontSize(7).fillColor('#b45309').font('Helvetica-Bold')
            .text('⚠', MARGIN + 54, blockY + 2)
        }

        // Title
        doc.fontSize(9).fillColor('#111827').font('Helvetica-Bold')
          .text(mr.title, MARGIN + 64, blockY, { width: CONTENT_W - 64 })

        doc.y = Math.max(doc.y, blockY + 14) + 4

        // Meta row
        const metaItems = [
          `${L.oem}: ${mr.oem}`,
          `${L.risk}: ${mr.risk}`,
          `${L.severity}: ${severityLabel(mr.severity, L)}`,
          `${L.version}: ${mr.version || '—'}`,
          `${L.changeStatus}: ${changeLabel(mr.changeStatus, L)}`,
          `${L.sourceDoc}: ${mr.sourceDoc || '—'}`,
        ]
        doc.fontSize(6.5).fillColor('#64748b').font('Helvetica')
          .text(metaItems.join('   |   '), MARGIN, doc.y, { width: CONTENT_W })

        doc.moveDown(0.5)

        // Description text - let it flow naturally over pages
        doc.x = MARGIN
        doc.fontSize(7.5).fillColor('#374151').font('Helvetica')
          .text(mr.text, { width: CONTENT_W })

        doc.moveDown(0.5)

        doc.moveDown(0.5)

        // Separator
        doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_W, doc.y).strokeColor('#e2e8f0').stroke()
        doc.moveDown(0.5)
      }
    }

    /* ================================================================ */
    /*  OVERLAPS & CONFLICTS                                             */
    /* ================================================================ */
    newPage()
    sectionHeader(L.conflictSection, '#b45309')

    if (conflicts.length === 0) {
      doc.fontSize(9).fillColor('#64748b').font('Helvetica').text(L.noConflicts)
    } else {
      // Decision rule
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#334155')
        .text(`${L.decisionRule}: `, { continued: true })
      doc.font('Helvetica').fillColor('#64748b').text(L.decisionRuleVal)
      doc.moveDown(0.8)

      for (const c of conflicts) {
        if (doc.y > 680) newPage()

        const y = doc.y
        doc.rect(MARGIN, y, CONTENT_W, 14).fill('#FFF3CD')
        doc.fontSize(8).fillColor('#92400e').font('Helvetica-Bold')
          .text(`${c.iatfChapter} — ${c.oems.join('  vs.  ')}`, MARGIN + 4, y + 3, { width: CONTENT_W - 8 })

        doc.y = y + 18
        doc.moveDown(0.25)

        doc.x = MARGIN
        doc.fontSize(7.5).fillColor('#78350f').font('Helvetica')
          .text(c.description, { width: CONTENT_W })
        doc.moveDown(0.5)

        if (doc.y > 720) newPage()

        doc.x = MARGIN
        doc.fontSize(7).fillColor('#065f46').font('Helvetica-Bold')
          .text(c.decision || L.conflictDecision, { width: CONTENT_W })
        
        if (c.reason) {
          doc.x = MARGIN
          doc.fontSize(6.5).fillColor('#475569').font('Helvetica-Oblique')
            .text(`${L.reason}: ${c.reason}`, { width: CONTENT_W })
        }
        
        doc.moveDown(0.7)

        doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_W, doc.y).strokeColor('#fde68a').stroke()
        doc.moveDown(0.5)
      }
    }

    /* ================================================================ */
    /*  DISCLAIMER                                                        */
    /* ================================================================ */
    if (doc.y > 720) newPage()
    doc.moveDown(2)
    doc.x = MARGIN
    doc.fontSize(6.5).fillColor('#94a3b8').font('Helvetica')
      .text(L.disclaimer, { width: CONTENT_W, align: 'center' })

    doc.end()
    await finished

    const pdfBuffer = Buffer.concat(chunks)

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="CSR_Matrix_Summary.pdf"',
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    console.error('[CSR Export] PDF generation failed:', err)
    return NextResponse.json({ error: 'PDF generation failed' }, { status: 500 })
  }
}
