import { NextRequest, NextResponse } from 'next/server'
import ExcelJS from 'exceljs'
import { isAuthenticatedFromRequest } from '@/lib/session/session'
import type { APLevel, ConfidenceLevel, FmeaRow, FmeaValidationResult, IssueSeverity } from '@/modules/fmea/types'

export const runtime = 'nodejs'
export const maxDuration = 60

const BLUE = 'FF1D4ED8'
const WHITE = 'FFFFFFFF'
const YELLOW_BG = 'FFFEF9C3'
const GRAY_BG = 'FFF8FAFC'
const RED_BG = 'FFFEE2E2'
const ORANGE_BG = 'FFFFEDD5'
const GREEN_BG = 'FFDCFCE7'
const DARK_GRAY = 'FF334155'
const COLS = 12

type FmeaAiFinding = {
  row_id: string
  ruleId: string
  title: string
  explanation: string
  recommended_action: string
  confidence: ConfidenceLevel
}

const thinBorder: Partial<ExcelJS.Borders> = {
  top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
  bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
  left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
  right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
}

interface ExportXlsxRequest {
  validationResult: FmeaValidationResult
  rows: FmeaRow[]
  originalWorkbookBase64?: string
  language?: 'de' | 'en'
}

const LABELS = {
  en: {
    title: 'FMEA Review Report',
    subtitle: 'AIAG/VDA Action Priority and structure validation',
    summary: 'Executive Summary',
    details: 'Review Details',
    issues: 'Validation Issues',
    metric: 'Metric',
    value: 'Value',
    generated: 'Generated',
    totalRows: 'Total Rows',
    validRows: 'Valid Rows',
    issueRows: 'Rows with Issues',
    completeness: 'Completeness Score (%)',
    apCompliance: 'AP Compliance Score (%)',
    apMismatches: 'AP Mismatches',
    processStep: 'Process Step',
    function: 'Function',
    failureMode: 'Failure Mode',
    failureEffect: 'Failure Effect',
    severity: 'S',
    failureCause: 'Failure Cause',
    occurrence: 'O',
    preventionControl: 'Prevention Control',
    detectionControl: 'Detection Control',
    detection: 'D',
    apCurrent: 'AP Current',
    apExpected: 'AP Expected',
    actionRecommended: 'Action Recommended',
    responsible: 'Responsible',
    targetDate: 'Target Date',
    sourceReference: 'Source Reference',
    validationStatus: 'Validation Status',
    issueList: 'Issues',
    reviewStatus: 'Review_Status',
    reviewIssues: 'Review_Issues',
    expectedApColumn: 'AP_Expected',
    aiFinding: 'AI_Finding',
    passed: 'Passed',
    hasIssues: 'Issues',
    disclaimer: 'This report was generated by IATF Solutions FMEA Reviewer. Always verify against the latest AIAG/VDA source documents.',
  },
  de: {
    title: 'FMEA-Pruefbericht',
    subtitle: 'AIAG/VDA Aktionsprioritaet und Strukturpruefung',
    summary: 'Zusammenfassung',
    details: 'Review-Details',
    issues: 'Validierungsprobleme',
    metric: 'Kennzahl',
    value: 'Wert',
    generated: 'Erstellt',
    totalRows: 'Gesamtzeilen',
    validRows: 'Gueltige Zeilen',
    issueRows: 'Zeilen mit Problemen',
    completeness: 'Vollstaendigkeit (%)',
    apCompliance: 'AP-Compliance-Score (%)',
    apMismatches: 'AP-Abweichungen',
    processStep: 'Prozessschritt',
    function: 'Funktion',
    failureMode: 'Fehlerart',
    failureEffect: 'Fehlerfolge',
    severity: 'S',
    failureCause: 'Fehlerursache',
    occurrence: 'O',
    preventionControl: 'Praeventionslenkung',
    detectionControl: 'Entdeckungslenkung',
    detection: 'D',
    apCurrent: 'AP Ist',
    apExpected: 'AP Soll',
    actionRecommended: 'Empfohlene Massnahme',
    responsible: 'Verantwortlich',
    targetDate: 'Zieldatum',
    sourceReference: 'Quellenreferenz',
    validationStatus: 'Validierungsstatus',
    issueList: 'Probleme',
    reviewStatus: 'Review_Status',
    reviewIssues: 'Review_Issues',
    expectedApColumn: 'AP_Expected',
    aiFinding: 'AI_Finding',
    passed: 'Bestanden',
    hasIssues: 'Probleme',
    disclaimer: 'Dieser Bericht wurde mit dem IATF Solutions FMEA Reviewer erstellt. Bitte stets mit den aktuellen AIAG/VDA-Quelldokumenten abgleichen.',
  },
} as const

function fill(color: string): ExcelJS.Fill {
  return { type: 'pattern', pattern: 'solid', fgColor: { argb: color } }
}

function merge(ws: ExcelJS.Worksheet, row: number, c1: number, c2: number) {
  ws.mergeCells(row, c1, row, c2)
}

function sectionHeader(ws: ExcelJS.Worksheet, row: number, text: string) {
  ws.getRow(row).height = 26
  merge(ws, row, 1, COLS)
  const cell = ws.getCell(row, 1)
  cell.value = text
  cell.font = { bold: true, size: 11, color: { argb: WHITE } }
  cell.fill = fill(BLUE)
  cell.alignment = { vertical: 'middle', horizontal: 'left' }
  cell.border = thinBorder
}

function tableHeader(ws: ExcelJS.Worksheet, row: number, headers: string[]) {
  ws.getRow(row).height = 24
  headers.forEach((header, index) => {
    const cell = ws.getCell(row, index + 1)
    cell.value = header
    cell.font = { bold: true, size: 9, color: { argb: WHITE } }
    cell.fill = fill(BLUE)
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true }
    cell.border = thinBorder
  })
}

function severityFill(severity: IssueSeverity) {
  if (severity === 'Critical') return RED_BG
  if (severity === 'High') return ORANGE_BG
  return YELLOW_BG
}

function apFill(ap?: APLevel) {
  if (ap === 'H') return RED_BG
  if (ap === 'M') return YELLOW_BG
  if (ap === 'L') return GREEN_BG
  return GRAY_BG
}

function styleReviewHeader(cell: ExcelJS.Cell) {
  cell.font = { bold: true, size: 9, color: { argb: WHITE } }
  cell.fill = fill(BLUE)
  cell.border = thinBorder
  cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true }
}

function safeSheetName(name: string) {
  return name.replace(/[\\/*?:[\]]/g, '_').slice(0, 31) || 'Review Summary'
}

function isFmeaAiFinding(value: unknown): value is FmeaAiFinding {
  if (!value || typeof value !== 'object') return false
  const candidate = value as Partial<FmeaAiFinding>
  return (
    typeof candidate.row_id === 'string' &&
    typeof candidate.title === 'string' &&
    typeof candidate.recommended_action === 'string'
  )
}

function getAiFindings(validationResult: FmeaValidationResult): FmeaAiFinding[] {
  return Array.isArray(validationResult.ai_findings)
    ? validationResult.ai_findings.filter(isFmeaAiFinding)
    : []
}

function issueSummaryRows(summary: FmeaValidationResult['issue_summaries'][number]): string {
  return summary.source_rows.length > 0
    ? summary.source_rows.join(', ')
    : summary.row_ids.join(', ')
}

export async function POST(request: NextRequest) {
  if (!(await isAuthenticatedFromRequest(request))) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body: ExportXlsxRequest
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const { validationResult, rows, originalWorkbookBase64, language = 'en' } = body

  if (!validationResult || !Array.isArray(rows)) {
    return NextResponse.json({ error: 'Invalid data' }, { status: 400 })
  }

  const L = LABELS[language] ?? LABELS.en
  const aiFindings = getAiFindings(validationResult)
  const issueSummaries = Array.isArray(validationResult.issue_summaries)
    ? validationResult.issue_summaries
    : []

  try {
    if (originalWorkbookBase64) {
      const wb = new ExcelJS.Workbook()
      const originalBuffer = Buffer.from(originalWorkbookBase64, 'base64')
      await wb.xlsx.load(originalBuffer as unknown as Parameters<typeof wb.xlsx.load>[0])
      wb.creator = 'IATF Solutions'
      wb.modified = new Date()

      const rowsBySheet = new Map<string, FmeaRow[]>()
      for (const row of rows) {
        const sheetRows = rowsBySheet.get(row.source_reference.sheet) ?? []
        sheetRows.push(row)
        rowsBySheet.set(row.source_reference.sheet, sheetRows)
      }

      for (const worksheet of wb.worksheets) {
        const sheetRows = rowsBySheet.get(worksheet.name)
        if (!sheetRows || sheetRows.length === 0) continue

        const startCol = worksheet.columnCount + 1
        const headerRowNumber = Math.max(
          1,
          Math.min(...sheetRows.map((row) => row.source_reference.row)) - 1,
        )
        const reviewHeaders = [L.reviewStatus, L.reviewIssues, L.expectedApColumn, L.aiFinding]
        reviewHeaders.forEach((header, index) => {
          const cell = worksheet.getCell(headerRowNumber, startCol + index)
          cell.value = header
          styleReviewHeader(cell)
          worksheet.getColumn(startCol + index).width = index === 1 || index === 3 ? 48 : 18
        })

        for (const fmeaRow of sheetRows) {
          const rowIssues = validationResult.issues.filter((issue) => issue.row_id === fmeaRow.id)
          const mismatch = validationResult.ap_mismatches.find((item) => item.row_id === fmeaRow.id)
          const rowAiFindings = aiFindings
            .filter((finding) => finding.row_id === fmeaRow.id)
            .map((finding) => `${finding.title}: ${finding.recommended_action}`)
            .join('\n')
          const values = [
            rowIssues.length ? L.hasIssues : L.passed,
            rowIssues.map((issue) => `[${issue.ruleId}/${issue.severity}] ${issue.message}`).join('\n'),
            mismatch?.expected_ap ?? fmeaRow.ap_current,
            rowAiFindings,
          ]

          values.forEach((value, index) => {
            const cell = worksheet.getCell(fmeaRow.source_reference.row, startCol + index)
            cell.value = value
            cell.border = thinBorder
            cell.alignment = { vertical: 'top', wrapText: true }
            if (index === 0 && rowIssues.length > 0) cell.fill = fill(YELLOW_BG)
            if (index === 2) cell.fill = fill(apFill(mismatch?.expected_ap ?? fmeaRow.ap_current))
          })
        }
      }

      const summaryName = safeSheetName(L.summary)
      const existingSummary = wb.getWorksheet(summaryName)
      if (existingSummary) wb.removeWorksheet(existingSummary.id)
      const summary = wb.addWorksheet(summaryName, { views: [{ state: 'frozen', ySplit: 4 }] })
      summary.columns = [{ width: 34 }, { width: 72 }]
      let row = 1
      merge(summary, row, 1, 2)
      const title = summary.getCell(row, 1)
      title.value = L.title
      title.font = { bold: true, size: 16, color: { argb: WHITE } }
      title.fill = fill(BLUE)
      title.alignment = { horizontal: 'center', vertical: 'middle' }
      summary.getRow(row).height = 36
      row += 2

      const summaryItems: [string, string | number][] = [
        [L.generated, new Date().toLocaleDateString(language === 'de' ? 'de-DE' : 'en-GB')],
        [L.totalRows, validationResult.rows_total],
        [L.validRows, validationResult.rows_valid],
        [L.issueRows, validationResult.rows_with_issues],
        [L.completeness, validationResult.completeness_score],
        [L.apCompliance, validationResult.ap_compliance_score],
        [L.apMismatches, validationResult.ap_mismatches.length],
      ]

      for (const [label, value] of summaryItems) {
        summary.getCell(row, 1).value = label
        summary.getCell(row, 1).font = { bold: true, size: 10, color: { argb: DARK_GRAY } }
        summary.getCell(row, 1).border = thinBorder
        summary.getCell(row, 2).value = value
        summary.getCell(row, 2).border = thinBorder
        row++
      }

      if (issueSummaries.length > 0) {
        row += 2
        tableHeader(summary, row, ['Summary', 'Affected Rows'])
        row++
        issueSummaries.forEach((item, index) => {
          summary.getCell(row, 1).value = item.summary
          summary.getCell(row, 2).value = issueSummaryRows(item)
          summary.getCell(row, 1).font = { size: 8 }
          summary.getCell(row, 2).font = { size: 8 }
          summary.getCell(row, 1).border = thinBorder
          summary.getCell(row, 2).border = thinBorder
          summary.getCell(row, 1).alignment = { vertical: 'top', wrapText: true }
          summary.getCell(row, 2).alignment = { vertical: 'top', wrapText: true }
          if (index % 2 === 1) {
            summary.getCell(row, 1).fill = fill(GRAY_BG)
            summary.getCell(row, 2).fill = fill(GRAY_BG)
          }
          row++
        })
      }

      row += 2
      tableHeader(summary, row, ['Row ID', 'Rule', 'Severity', 'Field', 'Message', 'Suggested'])
      row++
      validationResult.issues.forEach((issue, index) => {
        const values = [
          issue.row_id,
          issue.ruleId,
          issue.severity,
          issue.field,
          issue.message,
          issue.suggested_value ?? '',
        ]
        values.forEach((value, columnIndex) => {
          const cell = summary.getCell(row, columnIndex + 1)
          cell.value = value
          cell.font = { size: 8 }
          cell.border = thinBorder
          cell.alignment = { vertical: 'top', wrapText: true }
          if (index % 2 === 1) cell.fill = fill(GRAY_BG)
        })
        summary.getCell(row, 3).fill = fill(severityFill(issue.severity))
        row++
      })

      const buffer = await wb.xlsx.writeBuffer()
      return new NextResponse(buffer, {
        status: 200,
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'Content-Disposition': 'attachment; filename="FMEA_Review_Annotated.xlsx"',
          'Cache-Control': 'no-store',
        },
      })
    }

    const wb = new ExcelJS.Workbook()
    wb.creator = 'IATF Solutions'
    wb.created = new Date()

    const summary = wb.addWorksheet(L.summary)
    summary.columns = [{ width: 34 }, { width: 72 }]

    let row = 1
    merge(summary, row, 1, 2)
    const title = summary.getCell(row, 1)
    title.value = L.title
    title.font = { bold: true, size: 16, color: { argb: WHITE } }
    title.fill = fill(BLUE)
    title.alignment = { horizontal: 'center', vertical: 'middle' }
    summary.getRow(row).height = 36
    row++

    merge(summary, row, 1, 2)
    const subtitle = summary.getCell(row, 1)
    subtitle.value = L.subtitle
    subtitle.font = { italic: true, size: 10, color: { argb: DARK_GRAY } }
    subtitle.alignment = { horizontal: 'center', vertical: 'middle' }
    summary.getRow(row).height = 22
    row += 2

    const summaryItems: [string, string | number][] = [
      [L.generated, new Date().toLocaleDateString(language === 'de' ? 'de-DE' : 'en-GB')],
      [L.totalRows, validationResult.rows_total],
      [L.validRows, validationResult.rows_valid],
      [L.issueRows, validationResult.rows_with_issues],
      [L.completeness, validationResult.completeness_score],
      [L.apCompliance, validationResult.ap_compliance_score],
      [L.apMismatches, validationResult.ap_mismatches.length],
    ]

    for (const [label, value] of summaryItems) {
      summary.getCell(row, 1).value = label
      summary.getCell(row, 1).font = { bold: true, size: 10, color: { argb: DARK_GRAY } }
      summary.getCell(row, 1).border = thinBorder
      summary.getCell(row, 2).value = value
      summary.getCell(row, 2).font = { size: 10 }
      summary.getCell(row, 2).border = thinBorder
      row++
    }

    if (issueSummaries.length > 0) {
      row += 2
      tableHeader(summary, row, ['Summary', 'Affected Rows'])
      row++
      issueSummaries.forEach((item, index) => {
        summary.getCell(row, 1).value = item.summary
        summary.getCell(row, 2).value = issueSummaryRows(item)
        summary.getCell(row, 1).font = { size: 8 }
        summary.getCell(row, 2).font = { size: 8 }
        summary.getCell(row, 1).border = thinBorder
        summary.getCell(row, 2).border = thinBorder
        summary.getCell(row, 1).alignment = { vertical: 'top', wrapText: true }
        summary.getCell(row, 2).alignment = { vertical: 'top', wrapText: true }
        if (index % 2 === 1) {
          summary.getCell(row, 1).fill = fill(GRAY_BG)
          summary.getCell(row, 2).fill = fill(GRAY_BG)
        }
        row++
      })
    }

    row += 2
    merge(summary, row, 1, 2)
    summary.getCell(row, 1).value = L.disclaimer
    summary.getCell(row, 1).font = { size: 8, italic: true, color: { argb: 'FF94A3B8' } }
    summary.getCell(row, 1).alignment = { wrapText: true }
    summary.getRow(row).height = 34

    const details = wb.addWorksheet(L.details)
    details.columns = [
      { width: 14 },
      { width: 18 },
      { width: 28 },
      { width: 30 },
      { width: 8 },
      { width: 28 },
      { width: 8 },
      { width: 28 },
      { width: 28 },
      { width: 8 },
      { width: 12 },
      { width: 12 },
      { width: 32 },
      { width: 20 },
      { width: 14 },
      { width: 18 },
      { width: 16 },
      { width: 48 },
    ]

    row = 1
    details.mergeCells(row, 1, row, 18)
    const detailsTitle = details.getCell(row, 1)
    detailsTitle.value = L.details
    detailsTitle.font = { bold: true, size: 14, color: { argb: WHITE } }
    detailsTitle.fill = fill(BLUE)
    detailsTitle.alignment = { horizontal: 'center', vertical: 'middle' }
    details.getRow(row).height = 32
    row += 2

    const headers = [
      L.processStep,
      L.function,
      L.failureMode,
      L.failureEffect,
      L.severity,
      L.failureCause,
      L.occurrence,
      L.preventionControl,
      L.detectionControl,
      L.detection,
      L.apCurrent,
      L.apExpected,
      L.actionRecommended,
      L.responsible,
      L.targetDate,
      L.sourceReference,
      L.validationStatus,
      L.issueList,
    ]
    tableHeader(details, row, headers)
    details.views = [{ state: 'frozen', ySplit: row }]
    details.autoFilter = { from: { row, column: 1 }, to: { row, column: headers.length } }
    row++

    for (let i = 0; i < rows.length; i++) {
      const fmeaRow = rows[i]
      const rowIssues = validationResult.issues.filter((issue) => issue.row_id === fmeaRow.id)
      const mismatch = validationResult.ap_mismatches.find((item) => item.row_id === fmeaRow.id)
      const values = [
        fmeaRow.process_step,
        fmeaRow.function,
        fmeaRow.failure_mode,
        fmeaRow.failure_effect,
        fmeaRow.severity,
        fmeaRow.failure_cause,
        fmeaRow.occurrence,
        fmeaRow.prevention_control,
        fmeaRow.detection_control,
        fmeaRow.detection,
        fmeaRow.ap_current,
        mismatch?.expected_ap ?? fmeaRow.ap_current,
        fmeaRow.action_recommended,
        fmeaRow.responsible,
        fmeaRow.target_date,
        `${fmeaRow.source_reference.sheet}:${fmeaRow.source_reference.row}`,
        rowIssues.length ? L.hasIssues : L.passed,
        rowIssues.map((issue) => `[${issue.severity}] ${issue.message}`).join('; '),
      ]

      values.forEach((value, columnIndex) => {
        const cell = details.getCell(row, columnIndex + 1)
        cell.value = value
        cell.font = { size: 8 }
        cell.border = thinBorder
        cell.alignment = {
          vertical: 'top',
          horizontal: [5, 7, 10, 11, 12].includes(columnIndex + 1) ? 'center' : 'left',
          wrapText: true,
        }
        if (i % 2 === 1) cell.fill = fill(GRAY_BG)
      })

      details.getCell(row, 11).fill = fill(apFill(fmeaRow.ap_current))
      details.getCell(row, 12).fill = fill(apFill(mismatch?.expected_ap ?? fmeaRow.ap_current))
      if (rowIssues.length > 0) details.getCell(row, 17).fill = fill(YELLOW_BG)
      details.getRow(row).height = rowIssues.length ? 48 : 28
      row++
    }

    const issuesSheet = wb.addWorksheet(L.issues)
    issuesSheet.columns = [
      { width: 18 },
      { width: 14 },
      { width: 12 },
      { width: 18 },
      { width: 80 },
      { width: 16 },
    ]
    sectionHeader(issuesSheet, 1, L.issues)
    tableHeader(issuesSheet, 3, ['Row ID', 'Rule', 'Severity', 'Field', 'Message', 'Suggested'])
    row = 4
    validationResult.issues.forEach((issue, index) => {
      const values = [
        issue.row_id,
        issue.ruleId,
        issue.severity,
        issue.field,
        issue.message,
        issue.suggested_value ?? '',
      ]
      values.forEach((value, columnIndex) => {
        const cell = issuesSheet.getCell(row, columnIndex + 1)
        cell.value = value
        cell.font = { size: 8 }
        cell.border = thinBorder
        cell.alignment = { vertical: 'top', wrapText: true }
        if (index % 2 === 1) cell.fill = fill(GRAY_BG)
      })
      issuesSheet.getCell(row, 3).fill = fill(severityFill(issue.severity))
      issuesSheet.getRow(row).height = 34
      row++
    })

    const buffer = await wb.xlsx.writeBuffer()

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': 'attachment; filename="FMEA_Review.xlsx"',
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    console.error('[FMEA Export] Excel generation failed:', err)
    return NextResponse.json({ error: 'Excel generation failed' }, { status: 500 })
  }
}
